/**
 * Contract constants and configurations
 * Auto-generated by update-contract-types.ts
 */

export const CONTRACT_NAME = 'AccessContract';
export const CONTRACT_VERSION = 'AccessContract';
export const COMPILER_VERSION = '0.8.24';

// Resource Types enum (matches contract)
export enum ResourceType {
  URL = 1,
  IPFS = 2
}

// Event names for filtering
export const EVENT_NAMES = {
  ResourceCreated: 'ResourceCreated',
  AccessPurchased: 'AccessPurchased',
  Withdrawal: 'Withdrawal'
} as const;

// Gas limits (estimated)
export const GAS_LIMITS = {
  createResource: 500000,
  buyAccess: 300000,
  editResource: 200000,
  deactivateResource: 100000,
  deleteResource: 150000,
  withdraw: 100000,
  consumeUsage: 80000
} as const;

export type EventName = typeof EVENT_NAMES[keyof typeof EVENT_NAMES];
