/**
 * AccessContract SDK
 * Auto-generated by generate-index.ts
 * 
 * This package provides TypeScript types, constants, and utilities
 * for interacting with the AccessContract smart contract.
 */

// Contract constants and metadata
export * from './constants/contract';

// TypeScript type definitions
export * from './types/AccessContract';

// Event decoding utilities
export * from './utils/eventDecoding';

// Raw ABI export for advanced usage
export { default as ABI } from './abi/AccessContract.json';

// Re-export commonly used types for convenience
export type {
  Resource,
  Access,
  AccessContractEvent,
  RawLog
} from './types/AccessContract';

export {
  ResourceType,
  EVENT_NAMES,
  EVENT_TOPICS,
  GAS_LIMITS,
  getContractVersion
} from './constants/contract';

export {
  decodeEvent,
  decodeAccessContractEvent
} from './utils/eventDecoding';
